sprite $UTM_FW [86x42/16z] {
xPG7Tkim30Inm2vq_nl_pv8AXKzqUXdtDgB7CEqZ2Lx3Tl2yo8uMMH6fhBXTHaNfrd4MBIv7pMT42osHg6rqQrHlnpbcHwWSyXBrOz5yw3Sot9IMvIj6_wX7
NwTA8E66g8wfllVlfqMUBbMz2yPTvcvQrJbNk-wgyKF2TwUMMTSn5nE4cQidsMlWMGZqqL8q9StKh0NkH9rhXHzDFVeUZgp4HjJfwTQOrjwrWjLGLImEG2aO
crfgjnNjRNzkhPgRmHmM9UiwBPIdo7p-Qmdee37FySLGLTYqa-FHWmAkHds-KKMHBjCY5n268EdruElnKYvXZuPGBl6Jg6jKZ8i6yFz4lX7qXfdoxS6m_baP
4UNcrLOV4ul7Dqlu4XlMZTtqNQpuWciDFoSUMmE0CXr0ZXjznNdzimRV7diV_W4
}

